#!/bin/bash
set -e

if [ ! -d /tiddlywiki/mywiki ]; then
  tiddlywiki /tiddlywiki/mywiki --init server
fi

exec tiddlywiki /tiddlywiki/mywiki --server 8080 $:/core/save/all text/plain text/html ${USERNAME:-user} ${PASSWORD:-'wiki'} 0.0.0.0

